In [38]:
import numpy as np
from scipy.linalg import lu

In [44]:
def return_matrix():
    matrix = np.float64([[4,2,-1],[2,6,-3],[-8,-9,9]])
    return matrix
def return_b():
    b = np.array([-1,-8,14])
    return b
def return_l():
    l = np.float64([[1,0,0],[0.5,1,0],[-2,-1,1]])
    return l
def return_u():
    u = np.float64([[4,2,-1],[0,5,-2.5],[0,0,4.5]])
    return u

In [45]:
def PLU_matrix(matrix,b_mat):
    P,L,U = lu(matrix)
    print("P--->\n", P)
    print("L--->\n", L)
    print("U--->\n", U)
    b = P.dot(b_mat) 
    print("P*b-->\n", b )
    c = np.linalg.solve(L,b)
    print("L*c = P*b--> c:\n",c)
    x = np.linalg.solve(U,c)
    print("U*x = c --> x:\n",x)
    

In [46]:
def LU_matrix(matrix ,b_mat, l_mat, u_mat):
    a = matrix
    b = b_mat
    l = l_mat
    u = u_mat
    x = np.linalg.solve(a, b)
    print("genel çözüm x:", x)
    c = np.linalg.solve(l,b)
    print("LxC= B: c--> ",c)
    d = np.linalg.solve(u,c)
    print("U*x=c: x--> ",d)

In [47]:
PLU_matrix(return_matrix(),return_b())

P--->
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L--->
 [[ 1.          0.          0.        ]
 [-0.25        1.          0.        ]
 [-0.5        -0.66666667  1.        ]]
U--->
 [[-8.   -9.    9.  ]
 [ 0.    3.75 -0.75]
 [ 0.    0.    3.  ]]
P*b-->
 [14. -8. -1.]
L*c = P*b--> c:
 [14.  -4.5  3. ]
U*x = c --> x:
 [ 0.5 -1.   1. ]


In [48]:
LU_matrix(return_matrix(),return_b(), return_l(), return_u())

genel çözüm x: [ 0.5 -1.   1. ]
LxC= B: c-->  [-1.  -7.5  4.5]
U*x=c: x-->  [ 0.5 -1.   1. ]
