# SYSTEM OF EQUATIONS

In [11]:
import numpy as np
import math

In [12]:
def return_matrix():
    matrix = np.float64([[4,2,-1],[2,6,-3],[-8,-9,9]])
    return matrix
def return_b():
    matrix_b = np.float64([-1,-8,14])
    return matrix_b
def return_approotmatrix():
    xa =  np.float64([-1,1,1])
    return xa

In [13]:
def matrix_norm1(matrix):
    if abs(matrix[0])> abs(matrix[1]) and (abs(matrix[0]) > abs(matrix[2])):
        norm = abs(matrix[0])
    elif abs(matrix[1])> abs(matrix[0]) and (abs(matrix[1]) > abs(matrix[2])):
        norm = abs(matrix[1])
    else:
        norm = abs(matrix[2])
    return norm

def matrix_norm2(matrix):
    norm = 0
    row_sum = 0
    for i in range(3):
        for j in range(3):
            row_sum += abs(matrix[i][j])
        if row_sum > norm:
            norm = row_sum
        row_sum = 0
    return norm

In [14]:
def matrix_inverse(matrix):
    matrix_inverse = np.linalg.inv(matrix)
    print("Inverse matrix = ", matrix_inverse)
    return (matrix_inverse)


In [15]:
def matrix_condition_number(matrix):
    
    matrix_inv = matrix_inverse(matrix)
    print("Inverse A=\n", matrix_inv)
    A_norm = matrix_norm2(matrix)
    print("A norm = ", A_norm)
    A_inv_norm = matrix_norm2(matrix_inv)
    print("Inverse A norm = ", A_inv_norm)
    condition_number =  A_norm * A_inv_norm
    print("Condition number = ", condition_number)
    return (condition_number)

In [16]:
def matrix_solve(matrix,b):
    matrix_solve = np.linalg.solve(matrix,b)
    print("Roots x = \n", matrix_solve)
    return matrix_solve

In [17]:
def backward_error():
    A = return_matrix()
    b = return_b()
    xa = return_approotmatrix()
    mult_Axa = np.matmul(A,xa)
    print("A*xa =\n",mult_Axa)
    b_Axa = b- mult_Axa #b-A*xa
    print("b - A*xa =\n", b_Axa)
    backward_error = matrix_norm1(b_Axa)
    print("backward error= ",backward_error)
    return backward_error
def relative_backward_error():
    backwardError = backward_error()
    b_norm  = matrix_norm1(return_b())
    print("B norm = ", b_norm)
    relativeBackwardError = backwardError/b_norm
    print("Relative Backward Error = ",relativeBackwardError)
    return relativeBackwardError

In [18]:
def forward_error():
    xa = return_approotmatrix()
    x = matrix_solve(return_matrix(),return_b())
    x_xa = x - xa
    print("x-xa=\n", x_xa)
    forwardError = matrix_norm1(x_xa)
    print("Forward Error = ", forwardError)
    return forwardError
def relative_forward_error():
    forwardError = forward_error()
    x_norm = matrix_norm1(matrix_solve(return_matrix(),return_b()))
    print("x Norm = ", x_norm)
    relativeForwardError = forwardError/x_norm
    print("Relative forward error = ", relativeForwardError)
    return relativeForwardError

In [19]:
def error_magnification_factor():
    A = return_matrix()
    print("A:\n",A)
    b = return_b()
    print("b:\n",b)
    xa = return_approotmatrix()
    print("xa:\n",xa)
    emf = relative_forward_error()/relative_backward_error()
    print("Error magnification factor = ", emf)
    return emf

In [20]:
error_magnification_factor()

A:
 [[ 4.  2. -1.]
 [ 2.  6. -3.]
 [-8. -9.  9.]]
b:
 [-1. -8. 14.]
xa:
 [-1.  1.  1.]
Roots x = 
 [ 0.5 -1.   1. ]
x-xa=
 [ 1.5 -2.   0. ]
Forward Error =  2.0
Roots x = 
 [ 0.5 -1.   1. ]
x Norm =  1.0
Relative forward error =  2.0
A*xa =
 [-3.  1.  8.]
b - A*xa =
 [ 2. -9.  6.]
backward error=  9.0
B norm =  14.0
Relative Backward Error =  0.6428571428571429
Error magnification factor =  3.1111111111111107


3.1111111111111107

In [21]:
def f(x):
    return (1 + 2* math.cos(x) + math.cos(x)**2) *( 2 * math.sin(x)*math.cos(x))

In [43]:
f(45)

2.0799790471054997